### ISSUE TITLE
How to show hidden folders

### ISSUE THREAD

**Issue by mandokid** [lifegems/node-modules-context-menu#1]
this extension is very useful, but I can't find how to show the hidden folders. how can i do?

**Comment by leihucomeon** [comment]
> this extension is very useful, but I can't find how to show the hidden folders. how can i do?

the same question

**Comment by lifegems** [comment]
Hi @mandokid & @leihucomeon, thanks for reaching out.

To view the hidden folders again, follow these steps:
1. Open Preferences > Settings (or CMD/Ctrl + ,)
2. Navigate to Workspace > Text Editor > Files > Exclude
3. To show any of the hidden folders, Remove Exclude Items by clicking the small X
<img width="996" alt="Screen Shot 2021-03-07 at 11 01 14 AM" src="https://user-images.githubusercontent.com/17594309/110246164-80bf9c00-7f34-11eb-8930-9c330882e3aa.png">
